### ISSUE TITLE
As a reader I want to read news to know what's going on in the world

### ISSUE THREAD

**Issue by christopher-francisco** [chris-fa/news#3]
### AC
- [x] `GET /news` endpoint listed by recently updated
- [x] Development `Dockerfile` and `docker-compose.yml`.
- [x] Clear TDD setup
- [x] Create development seeds

**Comment by christopher-francisco** [comment]
Currently facing a setup problem for the database as it doens't exist before the test run

```
1) it returns posts sorted by modify date
SequelizeDatabaseError: Table 'news-server.posts' doesn't exist
    at Query.formatError (/Users/Chris/Developer/code/js/news/server/node_modules/sequelize/lib/dialects/mysql/query.js:247:16)
    at Query.handler [as onResult] (/Users/Chris/Developer/code/js/news/server/node_modules/sequelize/lib/dialects/mysql/query.js:68:23)
    at Query.Command.execute (/Users/Chris/Developer/code/js/news/server/node_modules/mysql2/lib/commands/command.js:30:12)
    at Connection.handlePacket (/Users/Chris/Developer/code/js/news/server/node_modules/mysql2/lib/connection.js:502:28)
    at PacketParser.onPacket (/Users/Chris/Developer/code/js/news/server/node_modules/mysql2/lib/connection.js:81:16)
    at PacketParser.executeStart (/Users/Chris/Developer/code/js/news/server/node_modules/mysql2/lib/packet_parser.js:77:14)
    at Socket.<anonymous> (/Users/Chris/Developer/code/js/news/server/node_modules/mysql2/lib/connection.js:89:29)
    at Socket.emit (events.js:180:13)
    at addChunk (_stream_readable.js:274:12)
    at readableAddChunk (_stream_readable.js:261:11)
    at Socket.Readable.push (_stream_readable.js:218:10)
    at TCP.onread (net.js:581:20)
```

**Comment by christopher-francisco** [comment]
Migrations and seeds are abstracted in commands. Implementations aren't actually migrations and seeds though
